<?php

namespace Database\Seeders;

use App\Models\Wallet;
use App\Models\WalletTransaction;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * SystemWalletSeeder
 *
 * Seeds the two system wallets once.  Safe to run multiple times (idempotent).
 *
 * System wallets are NOT tied to any user account.
 * They are identified solely by their phone_number (from config/admin.php)
 * and by the `name` column for human readability.
 *
 * Run via: php artisan db:seed --class=SystemWalletSeeder
 * Or add it to DatabaseSeeder::run().
 */
class SystemWalletSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedWallet(
            name:         'Primary Escrow',
            phone:        config('admin.primary.phone'),
            walletPrefix: config('admin.primary.wallet_prefix', 'PRM'),
        );

        $this->seedWallet(
            name:         'SyCash',
            phone:        config('admin.sycash.phone'),
            walletPrefix: config('admin.sycash.wallet_prefix', 'SYC'),
        );

        $this->command->info('System wallets seeded successfully.');
    }

    private function seedWallet(string $name, string $phone, string $walletPrefix): void
    {
        // Idempotent — skip if already exists
        if (Wallet::where('phone_number', $phone)->exists()) {
            $this->command->info("  [{$name}] already exists — skipped.");
            return;
        }

        DB::transaction(function () use ($name, $phone, $walletPrefix) {
            $wallet = Wallet::create([
                'name'          => $name,
                'user_id'       => null,          // no user owner
                'phone_number'  => $phone,
                'balance'       => 0.00,
                // wallet_number is auto-generated by the Wallet model booted() hook
            ]);

            // Audit trail — initial creation transaction
            WalletTransaction::create([
                'wallet_id'        => $wallet->id,
                'user_id'          => null,
                'type'             => 'system_wallet_init',
                'amount'           => 0.00,
                'previous_balance' => 0.00,
                'new_balance'      => 0.00,
                'description'      => "{$name} system wallet created",
                'transaction_id'   => strtoupper($walletPrefix) . '_INIT_' . now()->format('YmdHis') . '_' . Str::random(6),
                'status'           => 'completed',

            ]);

            $this->command->info("  [{$name}] wallet created — phone: {$phone}, number: {$wallet->wallet_number}");
        });
    }
}
