services:
  - type: web
    name: laravel-app
    runtime: php
    envVars:
      - key: RENDER_PORT
        value: 10000
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$RENDER_PORT
    plan: free
    healthCheckPath: /up
