sonar.php.coverage.reportPaths=coverage.xml
sonar.projectKey=abdurrahmanalze3bi_4th_year_projects_refractored
sonar.organization=abdurrahmanalze3bi
sonar.sources=app
sonar.tests=tests
sonar.language=php
