<?php

namespace App\Enums;

/**
 * REPLACE: app/Enums/ComplaintType.php
 *
 * CHANGE: Added NO_SHOW = 'no_show'
 * This type is used exclusively for auto-generated conflict complaints
 * when both driver and passenger press no-show within the 2-hour window.
 * Staff should treat these as highest priority.
 */
enum ComplaintType: string
{
    case TRIP_SAFETY        = 'trip_safety';
    case DRIVER_BEHAVIOR    = 'driver_behavior';
    case PASSENGER_BEHAVIOR = 'passenger_behavior';
    case RIDE_CANCELLATION  = 'ride_cancellation';
    case FINANCIAL_ISSUE    = 'financial_issue';
    case ACCOUNT_ISSUE      = 'account_issue';
    case TECHNICAL_ISSUE    = 'technical_issue';
    case NO_SHOW            = 'no_show';      // ← NEW: auto-created conflict complaint
    case OTHER              = 'other';

    public function label(): string
    {
        return match ($this) {
            self::TRIP_SAFETY        => 'أمان الرحلة',
            self::DRIVER_BEHAVIOR    => 'سلوك السائق',
            self::PASSENGER_BEHAVIOR => 'سلوك الراكب',
            self::RIDE_CANCELLATION  => 'إلغاء الرحلة',
            self::FINANCIAL_ISSUE    => 'مشكلة مالية',
            self::ACCOUNT_ISSUE      => 'مشكلة في الحساب',
            self::TECHNICAL_ISSUE    => 'عطل تقني',
            self::NO_SHOW            => 'تعارض تقارير الغياب',
            self::OTHER              => 'أخرى',
        };
    }

    /**
     * Whether this complaint type was auto-generated by the system
     * (not submitted by a user manually).
     * Staff can use this to filter and prioritise the queue.
     */
    public function isAutoGenerated(): bool
    {
        return $this === self::NO_SHOW;
    }
}
